### ISSUE TITLE
WG Kick-Off - 06th July

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/BlockchainPublicAddress#2]
Dear WG participants,

Would like to have a kick-off meeting on Thursday next week (06-July) to begin activities within this WG.

I will provide som agenda within this Issue.
From the beginning, main objectives are:
- Agree on meetings schedule (will provide some slots). In principle bi-weekly basis.

> Tuesdays:
> 10:00 - 11:00
> 13:00 - 14:00

> Wednesdays:
> 11:00 - 12:00

> Thursdays:
> 12:00 - 13:00
> 13:00 - 14:00

- Volunteers for Maintainers and CodeOwners

- Provide initial Use Cases document

> [Issue#3](https://github.com/camaraproject/BlockchainPublicAddress/issues/3)

- Provide initial proposal input as per https://github.com/camaraproject/WorkingGroups/pull/154

> [Issue#6](https://github.com/camaraproject/BlockchainPublicAddress/issues/6)

**Comment by sebKoeller** [comment]
Sounds good, what time though?

**Comment by PedroDiez** [comment]
> Sounds good, what time though?

Hi Seb, I sent and invite for tomorrow June 6th, 13:00 - 14:00 CEST.
Here is the MS teams link in case you have not received it.
[Click Here to Join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDEzMTg1MTctOWE4NC00ZjI3LTlhYTMtNWRlNWExNDRmNTNh%40thread.v2/0?context=%7b%22Tid%22%3a%229744600e-3e04-492e-baa1-25ec245c6f10%22%2c%22Oid%22%3a%2219764050-b5d5-4991-9f15-d10905a94c08%22%7d)

**Comment by PedroDiez** [comment]
@sebKoeller Are you already subscribed to this WG? If not the case (I do not have your mail contact address)

Would you please send an empty email to [all+subscribe@lists.camaraproject.org](mailto:all+subscribe@lists.camaraproject.org). That initiates the process. 
Once done please contact Markus (DT) for him to be able to subscribe you to the WG [Markus.Kuemmerle@telekom.de](mailto:Markus.Kuemmerle@telekom.de)

**Comment by PedroDiez** [comment]
Need to re-schedule next meeting to 20th July, due to internal meeting.
@sebKoeller I comment to you in advance, seems you are the one has access so far to this repo.

I will generate meeting schedule

**Comment by PedroDiez** [comment]
Facility Tool: https://editor.swagger.io/

**Comment by PedroDiez** [comment]
Close this issue as informative for Kick-Off
