### ISSUE TITLE
Add Aleph Zero to the default Protocol List

### ISSUE THREAD

**Issue by JulianUeding** [camaraproject/BlockchainPublicAddress#59]
**Problem description**
Aleph Zero is interested in supporting the BlockchainPublicAddress API working group under the Camara Foundation by providing testing environments. To enable seamless testing, Aleph Zero requires its protocol to be listed in the available protocol list of the API. This listing will allow developers and stakeholders to utilize Aleph Zero's blockchain as part of their testing processes, improving the API's robustness and compatibility with various blockchain protocols.

**Possible evolution**
Incorporating Aleph Zero into the API's available protocol list could streamline testing processes, encourage more extensive adoption, and allow for efficient API integrations with different blockchains. Over time, this could also open up possibilities for deeper feature support, enhancing its utility and reach.

**Alternative solution**
An alternative approach would be for Aleph Zero to run an independent testing environment outside the API's protocol list. While this could provide isolated testing, it would not facilitate direct interaction with the API, making it less effective for widespread and collaborative testing efforts.

**Additional context**
Including Aleph Zero in the protocol list will enable feedback and improvements that cater to a broader range of blockchain protocols, ultimately benefiting the Camara Foundation’s goals for the API's adoption and performance.

**Comment by PedroDiez** [comment]
Network to be considered is the MainNet: 41455 (0xa1ef)	AZERO

https://chainlist.org/?search=Aleph+Zero&testnets=false

**Comment by PedroDiez** [comment]
Closed as PR #60 merged
