### ISSUE TITLE
Baseline Proposal

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/BlockchainPublicAddress#6]
Initial Proposal considers:
- Endpoint to fetch blockchain public addresses linked per a given phoneNumber
- Endpoint to bind a blockhain public address to a phoneNumber
- Endpoint to unbind a  blockhain public address <-> phoneNumber

Baseline proposal provided in [PR#5](https://github.com/camaraproject/BlockchainPublicAddress/pull/5)

**Comment by sebKoeller** [comment]
Why would the "currency" parameter be necessary?
The chain-Id is already defined by its own field and since you can send all sorts of tokens on smart contract blockchains, there's no real need to return a "currency" parameter as well, in my opinion.

**Comment by sebKoeller** [comment]
Also, there's was critique that if anyone can request the address of any phone number, then this would open up many possibilities for scammers.
While this is true, personally, I don't think it's much of an issue since this is already the case just with phone numbers.
Scammers already send SMS with fraudulent intentions, or call you and impersonate some company's customer service.

**Comment by sebKoeller** [comment]
And regarding security, perhaps we could require a signature hash & message hash inside the POST request data field.
This way, you'd have to prove that you actually own the address that you want to connect.

**Comment by PedroDiez** [comment]
You mean in both GET and POST requests?

**Comment by PedroDiez** [comment]
@sebKoeller, @grgpapadopoulos 

One point to talk today, From TEF we are working in an internal MVP to show initial experience with this API.

I would like then to merge initial proposal as v0.1, setting currency as optional Array (even we discuss it further) and for sure the consents management track.

Thus, we as WG also have an initial baseline spec based to work on it

**Comment by PedroDiez** [comment]
Closed as PR#5 is merged
